# Generated by Django 3.0.2 on 2020-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promogroup',
            name='participant',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='menu',
            field=models.CharField(default='main', help_text='main, new promo group question 1, manage groups, manage group, edit name, delete group, add participant', max_length=100, verbose_name='Menu'),
        ),
    ]
